name: TNTWars
version: '${project.version}'
author: Jeroeno_Boy
description: The Minecraft TNTWars Plugin
main: com.jeroenvdg.tntwars.TNTWars
api-version: '1.21'
depend: [FastAsyncWorldEdit]
softdepend: [PlaceholderAPI]
commands:
  game:
    description: Admin commands
    usage: Type /game
    permission: tntwars.game
  mapmanager:
    description: Edit maps
    usage: Type /mm
    permission: tntwars.mapmanager
    aliases: [mm]
  team:
    description: Select team
    usage: Type /team
    aliases: [teams, leave, leaveteam]
  votemap:
    description: Vote for map
    usage: Type /votemap
    aliases: [map, maps]
  shop:
    description: Open shop menu.
    usage: Type /shop
  teamchat:
    description: Change chat mode to teamchat
    usage: Type /teamchat
    aliases: [tc]
  booster:
    description: Activate booster
    usage: Type /booster
    aliases: [boosters]
  profile:
    description: Open Profile
    usage: Type /profile
  like:
    description: Like a map
    usage: /like
  dislike:
    description: Dislike a map
    usage: /dislike
  boost:
    description: Activate a booster
    usage: /boost [player]
  settings:
    description: Change your settings
    usage: /settings